FROM openjdk:17
ADD target/SpringBootEsercizio2FilippoAprile.jar app1.jar
ENTRYPOINT [ "java", "-jar","app1.jar" ]

#docker build -t NOME_IMAGE .


#docker run --name NOME_CONTAINER -d -p 8080:8080 NOME_IMAGE